{{- if empty .Values.bdr.serviceAccountSecretName }}
{{- if empty (lookup "v1" "Secret" .Release.Namespace "{{ include eric-oss-sftp-filetrans.name . }}-bdr-svc-account-secret") }}
#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-sftp-filetrans.name" . }}-bdr-svc-account-secret
  labels:
     {{- include "eric-oss-sftp-filetrans.labels" . | nindent 4 }}
  annotations:
     {{- include "eric-oss-sftp-filetrans.annotations" . | nindent 4 }}
type: Opaque
data:
  sftp-bdr-secret-key: {{ template "eric-oss-sftp-filetrans-bdrReadWriteSecretKey" . }}
  sftp-bdr-access-key: {{ template "eric-oss-sftp-filetrans-bdrReadWriteAccessKey" . }}
  parser-bdr-secret-key: {{ template "eric-oss-sftp-filetrans-bdrReadOnlySecretKey" . }}
  parser-bdr-access-key: {{ template "eric-oss-sftp-filetrans-bdrReadOnlyAccessKey" . }}

{{- end }}
{{- end }}